### ISSUE TITLE
Create common model for Issues

### ISSUE THREAD

**Issue by ruromero** [RHEcosystemAppEng/crda-backend#28]
At this point, the data model to show in the HTML report seems to be stable. It will be simpler to create a specific model for that in the application that can be also used in the response JSON instead of the `rawData` that is currently being returned.

The idea is that each vulnerability adaptor (Snyk, Tidelift, etc.) converts its custom response into a common data model. That will simplify the clients and the html template processing.

It will also address the problem introduced in PR #21 where a lot of dependencies to the Jackson data model where added making it hard to resolve during the native compilation.

A summary will also be helpful for the clients that are expected to render it. The summary will contain information about the scanned and transitive dependencies along with the vulnerabilities found for each severity.

The Issue data model will show:

- Title (description of the issue)
- Source (vulnerability provider)
- Cvss Vector
- Severity
- CVEs

**Comment by TomerFi** [comment]
Dropping this here for reference to the current state:

This is the type used by the current CLI for deserializing the old response:
https://github.com/fabric8-analytics/cli-tools/blob/main/pkg/analyses/driver/matcher.go#L56

This is how the current CLI parses the deserialized response:
https://github.com/fabric8-analytics/cli-tools/blob/main/pkg/analyses/summary/helpers.go#L59
