### ISSUE TITLE
Accept SBOM files for Dependency Analysis

### ISSUE THREAD

**Issue by ruromero** [RHEcosystemAppEng/crda-backend#37]
CycloneDX Software Bill of Materials (SBOM) containing the aggregate of all direct and transitive dependencies of a project. CycloneDX is a lightweight software bill of materials (SBOM) standard designed for use in application security contexts and supply chain component analysis.

As a backend consumer I want to get a dependency analysis report using an SBOM json file. This will help having a common entry point regardless of the package manager

**Comment by TomerFi** [comment]
> As a backend consumer I want to get a dependency analysis report using an SBOM json file. This will help having a common entry point regardless of the package manager

I just want to point out that we haven't settled on the format for the other supported package managers yet. Assuming we can get them all to do _SBOM_, than this point would make more sense.

---

I would also want to emphasize that the _SBOMs_, on the contrary from _Dependency Trees_, are project-scope manifests. Excluding specific packages from their content, might not be applicable out-of-the-box using existing tools. For instance, the [cyclonedx-maven-plugin](https://github.com/CycloneDX/cyclonedx-maven-plugin), used for creating an _SBOM_ for _Maven_ projects, has no option to exclude specific packages. Excluding specific packages is mandatory for _inline-ignoring_ support.

For _Maven_ projects, switching to _SBOM_ means we will have to either manually cherry-pick the ignored dependencies out of the _SBOM_ on the client side before sending it to the backend. Or propagate the ignored list to the backend as part of the initial request, and have the backend manually exclude them from the requests propagated to the various providers. The latter is the approach taken with the previous backend.

Both of these approaches should work. But our current approach uses _Apache's_ own _Dependency-Plugin_ [list goal](https://maven.apache.org/plugins/maven-dependency-plugin/list-mojo.html), to create a _Dependency Tree_ in the form of a _Dot Graph_. Which has an out-of-the-box option to exclude dependencies from the tree using a command line flag.

So unless we use _SBOM_ for all other supported package managers. Or unless we something else to gain from switching to _SBOM_. I would be inclined to stick to _Dot Graphs_ for _Maven_ projects.

That doesn't mean we need to drop the _SBOM_ support suggested in #38. But I think it should be made clear that we haven't settled on _SBOM_ just yet.
